### PR TITLE
Welcome Microverse Project

### PR DESCRIPTION
**Pull request by Sami-Ullah-Tufail**
We have

- The setup of the branch in the master branch
- The complete setup of HTML-CSS liters
- The setup of the .gitignore file

### CODE REVIEW

**Review by ouasamine — CHANGES_REQUESTED** [review]
Hi @samiullah12345678 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights
- Nice work adding the `.gitignore` file ✔️ 

## Note: 
Please note that I had to look in your repo for the previous review because you used a different PR to ask for a re-review, **Remember that you need to always use the same pull request as in your initial review and that you SHOULD NOT create new ones nor you should close, merge or delete a PR before it has been approved by a code reviewer, please refer to this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/how_to_ask_for_a_code_review.md) for guidance.**

 ## Required Changes ♻️

- [x] Nice work adding the README as required by the previous reviewer however, since you added the README file in a different branch I can't access the file and therefore can't make inline comments so I am going to list all the changes required for the README here.
  - You need to remove the logo or replace it with your own if you have one.
  - Make sure to remove the liver version section deployment is not part of the project's requirements.
  - The license link at the bottom of the file is not working currently, make sure to add a license to your project.
  - Make sure to remove descriptive lines, they are meant to guide you through the README setup and you should remove the after copying the template, like this one `Mention all of the collaborators of this project.`
  - You need to add your contact info under the "collaborators" section instead of the placeholder text.
  - Make sure to add a valid call to action under "show your support section".
  - Make sure to add a valid acknowledgement to your README

- [x] As requested by the previous reviewer, you need to add a summary to your PR and it should be valid and descriptive, the summary that you have now is not professional because you just copy-pasted the whole README in it
  > **Friendly reminder**: You should make sure that your repository looks professional before review. Please take a step back apply 5 simple rules from this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) (it will be easy as you can use a template provided there).


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Sami-Ullah-Tufail** [comment]
I have fixed the problems regarding the READme and the pull request

**Review by wayungi — CHANGES_REQUESTED** [review]
Hi @samiullah12345678 , 

image

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- [x] All linter checks passing ✔️ 
- [x]  Correct GitHub flow ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._
- [x] Good adding your README FILE as requested by previous reviewers. Since the file in not in the PR, I will add my comments here.

- [x] Your README has a broken image link. Please remove the logo completely or fix it.
logo

- [x] Your Live demo section still has guiding text and it's not edited. Kindly delete this section since it's not required for this project or edit it as advised below: 🤝 
demo

- [x] Please edit your `AUTHORS` section to reflect one contributor since its an individual project.
authors

- [x] Your LICENCE link is broken. Please add the license in this branch so that it can be accessible. [Add license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)
lic


## Optional suggestions
- [ OPTIONAL] Your project does not use React, PostgreSQL & express. Please edit this section appropriately to include your stack which is HTML & CSS only on the client side.
stack
- [x] Your PR title is not descriptive. Kindly add descriptive titles for your PR
title

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @samiullah12345678, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* Good commit messages. :heavy_check_mark:
* No linter errors. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* Professional README file. :heavy_check_mark:
* PR has a good title and summary :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._
- [x] It is very important and required for you to have a README file. Rather that delete your README file, please kindly implement all the changes requested for by the previous reviewer. Kindly see a Demo of a professional README file below:

https://user-images.githubusercontent.com/83360636/218715072-2b2d3a49-8219-4939-b350-45cc950f7f7a.gif

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by IngDavidTM — CHANGES_REQUESTED** [review]
## Hi @samiullah12345678  🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.



## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] Your README file is excellent, but as previously mentioned, it's important to include a **link** to the LICENSE in the file, not the LICENSE. Please ensure that you add the necessary link to comply with the project requirements.
To make this possible, my suggestion is to create a file named "LICENSE" without any extensions, such as ".txt". This will ensure that the file is recognized as the license for the project and can be easily linked to the README file. Inside that file you should add the information about the LICENSE

Screenshot from 2023-03-23 06-03-56


- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by KanzaTahreem — APPROVED** [review]
# Approved 🥳

Hi @samiullah12345678  👋

Great work implementing the changes suggested by previous reviewer. I would like to express mydeep appreciation for the time and effort you dedicated to this project 💪

**_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**



## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Great work using the right GitHub Flow 
-  ✅ Your README looks professional, well done!
-  ✅ Commits are descriptive, good work.
-  ✅ Linters are working properly, great job! 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Good job with the README 🥇Please consider removing the placeholders from every section/heading. These placeholders are there to help you with what to add in the respective section ⚒ Please consider removing these placeholders to make your README even more professional. As an example, you can go through [this README](https://github.com/KanzaTahreem/Hello-React-Frontend) but please make sure that the content is customized according to the project you are working on. I know you can do that 💪

image


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
